config/routes.rb
Rails.application.routes.draw do
  root 'people#index'

  get 'auth-in-vk', to: 'auth_services#vk'
  resources :people
  resources :analyses, only: [:index, :show]
end

app/models/person.rb
class Person < ApplicationRecord
  has_many :analyses, dependent: :destroy

  validates :full_name, presence: true

  def assign_fields(fields)
    fields.each do |k, v|
      splitten_key = k.split('_')
      p_key = splitten_key.shift
      c_key = splitten_key.join('_')
      metadata[p_key] = {} unless metadata.key?(p_key)
      metadata[p_key][c_key] = v
    end
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, except: %i[index new create]
  before_action :vk_attrs, only: [:edit], if: -> { request.get? }

  def index
    @people = Person.all
  end

  def show; end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(person_params)

    if @person.save
      redirect_to @person
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    @person.assign_fields(vk_params) if vk_params.present?
    if @person.update(person_params)
      redirect_to @person
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @person.destroy

    redirect_to root_path
  end

  private

  def set_person
    @person = Person.find(params[:id])
  end

  def person_params
    params.require(:person).permit(:full_name, :birthday, :city, :region, :country)
  end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= form_with model: @person do |form| %>
  <div>
    <%= form.label :full_name %><br>
    <%= form.text_field :full_name %><br>
    <% @person.errors.full_messages_for(:full_name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :birthday %><br>
    <%= form.date_field :birthday %>
  </div>
  <div>
    <%= form.label :country %><br>
    <%= form.country_select :country, selected: 'RU' %>
  </div>
  <div>
    <%= form.label :region %><br>
    <%= form.text_field :region %>
  </div>
  <div>
    <%= form.label :city %><br>
    <%= form.text_field :city %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/people/_vk_form.html.erb
<h1>VK Fields</h1>
<%= form_with model: @person do |form| %>
  <div>
    <%= form.label :user %><br>
    <%= form.select :vk_user_id, @vk_users, include_blank: true, disabled: @vk_users.blank? %>
  </div>
  <div>
    <%= form.label :country %><br>
    <%= form.select :vk_country_id, @vk_countries, include_blank: true, disabled: @vk_countries.blank? %>
  </div>
  <div>
    <%= form.label :region %><br>
    <%= form.select :vk_region_id, @vk_regions, include_blank: true, disabled: @vk_regions.blank? %>
  </div>
  <div>
    <%= form.label :city %><br>
    <%= form.select :vk_city_id, @vk_cities, include_blank: true, disabled: @vk_cities.blank? %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Edit Tracked Person</h1>
<%= render "form", person: @person %>
<% if !@person.new_record? %>
  <%= render "vk_form", person: @person %>
<% end %>

app/views/people/index.html.erb
<h1>Tracked People</h1>
<ul>
  <% @people.each do |person| %>
    <li>
      <%= link_to(person.full_name, person) %>
    </li>
  <% end %>
</ul>
<%= link_to "New Tracked Person", new_person_path %><br>
<%= link_to "Analyses", analyses_path %>

app/views/people/new.html.erb
<h1>New Tracked Person</h1>
<%= render "form", person: @person %>

app/views/people/show.html.erb
<h1><%= @person.full_name %></h1>
<p>Birthday: <%= @person.birthday&.strftime('%d.%m.%Y') %></p>
<p>Country: <%= @person.country %></p>
<p>Region: <%= @person.region %></p>
<p>City: <%= @person.city %></p>
<ul>
  <% if @person.metadata.dig('vk', 'user_id') %>
    <li><%= link_to "Person in VK", "https://vk.com/id#{@person.metadata['vk']['user_id']}", target: :_blank %></li>
  <% end %>
  <li><%= link_to "Edit", edit_person_path(@person) %></li>
  <li><%= link_to "Destroy", person_path(@person),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></li>
</ul>